### PR TITLE
Cleaning discrete gw sw meas data

### PR DESCRIPTION
**Pull request by msleckman**
This PR adds several adjustments to capture all discrete nwis sw and gw data for visualization purposes.

Associated with issue #57 and must be merged after #56 

#### Changes:

renamed `sites_along_waterbody.R` --> `process_nwis_data.R`
renamed `4_exports` folder --> `4_outputs`
**new targets:** 
`p2_nwis_meas_gw_data`

**new functions:**
standardized `add_stream_order()` for adding stream order category to discrete and continuous (dv) sw sites 
New more standard `join_site_spatial_info()` that performs spatial join with target `p2_nwis_sites_in_watersheds_sf` (i.e. all sites in watersheds) and give info the data records dataset such as `lat` `lon` and `site_type` 

**discrete data outputs**
`4_outputs/out/p4_nwis_meas_sw_data_rds`
`4_outputs/out/p4_nwis_meas_gw_data_rds`

#### numbers: (ref [gist L109](https://gist.github.com/msleckman/762286d6013e0f26d3d1127e4eedd228))

```
> ## count of individual measurements
> meas_sw_clean %>% count() %>% pull(n)
[1] 48083
> meas_gw_clean %>% count() %>% pull(n)
[1] 64435
> ## count of unique sites
> summarized_meas_gw %>% ungroup() %>%  count() %>% pull(n)
[1] 3322
> summarized_meas_sw %>% ungroup() %>%count() %>% pull(n)
[1] 635
```
Over 3,000 discrete sites for gw collected a total of 64435 data records, while only 635 discrete sites for sw collecting a total of 48083.

### CODE REVIEW

**Review by cnell-usgs — CHANGES_REQUESTED** [review]
Again, I think rather than creating long form targets, we need site-level targets that gather site info like location, streamorder, data type, lake, etc. I suggest eitther (1) creating separate targets for each data type at the site-level, or (2) creating a master site-level target that provides this information for all sites, including what type of data are available there. This will be very useful for developing summaries for each site, lake, and making visuals.

**Comment by ceenell** [comment]
Also do not commit the exported data files to the repo

**Review by cnell-usgs — APPROVED** [review]

**Comment by ceenell** [comment]
Sure go ahead and merge once the conflicts are addressed. I will work on adding the site-level target.

**Comment by ceenell** [comment]
By tidy site-level target I mean a dataframe where there is a single row for each site, and related info in the columns. It would be useful to store important site info, like streamorder

**Comment by msleckman** [comment]
Following a lengthy process of attempting to resolve merge conflicts that appeared on three files `2_process_site_data.R`, `2_process_lake_tribs.R`, and 12_process/src/saline_lakes_waterbody.R` which were ultimately removed in this PR to resolve https://github.com/USGS-VIZLAB/saline-lakes/pull/66

This PR still did not make the conflict in `2_process_lake_tribs.R` go away. As a result I have deleted it in the branch (renamed it to a file that is not being tracked by this PR) in this commit https://github.com/USGS-VIZLAB/saline-lakes/pull/58/commits/0203c138adb5e4c5a522d22ff8616e1878d6c6f0.

Will add via a new PR #67

- [ ] Verify that USGS-R/main run after mergin this PR #58 and the #67.

**Pull request merged**
